In [1]:
# !nvidia-smi

In [2]:
# from pynvml import *
# nvmlInit()
# h = nvmlDeviceGetHandleByIndex(0)
# info = nvmlDeviceGetMemoryInfo(h)
# print(f'total    : {info.total}')
# print(f'free     : {info.free}')
# print(f'used     : {info.used}')

In [8]:
!pip install tensorflow==2.7.1 tensorflow-gpu==2.7.1 opencv-python matplotlib

     |████████████████████████████████| 495.2 MB 9.5 kB/s eta 0:00:01    |█████▏                          | 79.1 MB 2.3 MB/s eta 0:03:04     |███████████████████████▏        | 358.4 MB 3.6 MB/s eta 0:00:38
     |████████████████████████████████| 495.2 MB 9.8 kB/s eta 0:00:01
  Using cached opencv_python-4.6.0.66-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.9 MB)
     |████████████████████████████████| 2.4 MB 5.5 MB/s eta 0:00:01
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     |████████████████████████████████| 1.3 MB 7.8 MB/s eta 0:00:01
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
     |████████████████████████████████| 124 kB 14.4 MB/s eta 0:00:01
     |████████████████████████████████| 463 kB 14.6 MB/s eta 0:00:01
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
     |████████████████████████████████| 5.9 MB

In [1]:
# Import standard dependencies

import cv2
import os
import random
import numpy as np
from matplotlib import pyplot as plt

# Import tensorflow dependencies - Functional API

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Layer, Conv2D, Dense, MaxPooling2D, Input, Flatten
import tensorflow as tf

In [2]:
# Avoid OOM errors by setting GPU Memory Consumption Growth

gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus: 
    tf.config.experimental.set_memory_growth(gpu, True)

2022-10-25 20:04:05.857498: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-25 20:04:05.877316: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/aneesh/anaconda3/envs/jupyter_env/lib/python3.9/site-packages/cv2/../../lib64:
2022-10-25 20:04:05.877334: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [11]:
# Setup paths
POS_PATH = os.path.join('data', 'positive')
NEG_PATH = os.path.join('data', 'negative')
ANC_PATH = os.path.join('data', 'anchor')

In [12]:
# Make the directories
os.makedirs(POS_PATH)
os.makedirs(NEG_PATH)
os.makedirs(ANC_PATH)

## Collecting Positives and Anchors

In [ ]:
# http://vis-www.cs.umass.edu/lfw/

In [17]:
# Uncompress Tar GZ Labelled Faces in the Wild Dataset
!tar -xf lfw.tgz

In [18]:
# Move LFW Images to the following repository data/negative
for directory in os.listdir('lfw'):
    for file in os.listdir(os.path.join('lfw', directory)):
        EX_PATH = os.path.join('lfw', directory, file)
        NEW_PATH = os.path.join(NEG_PATH, file)
        os.replace(EX_PATH, NEW_PATH)

### Collectig Positive & Anchor Images

In [19]:
# Import uuid library to generate unique image names
import uuid

In [20]:
os.path.join(ANC_PATH, '{}.jpg'.format(uuid.uuid1()))

'data/anchor/80ba081a-5176-11ed-aeb1-91af58059082.jpg'

In [33]:
# Establish a connection to the webcam
cap = cv2.VideoCapture(0)
while cap.isOpened(): 
    ret, frame = cap.read()
   
    # Cut down frame to 250x250px
    frame = frame[120:120+250,200:200+250, :]
    
    # Collect anchors 
    if cv2.waitKey(1) & 0XFF == ord('a'):
        # Create the unique file path 
        imgname = os.path.join(ANC_PATH, '{}.jpg'.format(uuid.uuid1()))
        # Write out anchor image
        cv2.imwrite(imgname, frame)
    
    # Collect positives
    if cv2.waitKey(1) & 0XFF == ord('p'):
        # Create the unique file path 
        imgname = os.path.join(POS_PATH, '{}.jpg'.format(uuid.uuid1()))
        # Write out positive image
        cv2.imwrite(imgname, frame)
    
    # Show image back to screen
    cv2.imshow('Image Collection', frame)
    
    # Breaking gracefully
    if cv2.waitKey(1) & 0XFF == ord('q'):
        break
        
# Release the webcam
cap.release()
# Close the image show frame
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x55806d5017a0) is not the object's thread (0x55806d8e21c0).
Cannot move to target thread (0x55806d5017a0)

QObject::moveToThread: Current thread (0x55806d5017a0) is not the object's thread (0x55806d8e21c0).
Cannot move to target thread (0x55806d5017a0)

QObject::moveToThread: Current thread (0x55806d5017a0) is not the object's thread (0x55806d8e21c0).
Cannot move to target thread (0x55806d5017a0)

QObject::moveToThread: Current thread (0x55806d5017a0) is not the object's thread (0x55806d8e21c0).
Cannot move to target thread (0x55806d5017a0)

QObject::moveToThread: Current thread (0x55806d5017a0) is not the object's thread (0x55806d8e21c0).
Cannot move to target thread (0x55806d5017a0)

QObject::moveToThread: Current thread (0x55806d5017a0) is not the object's thread (0x55806d8e21c0).
Cannot move to target thread (0x55806d5017a0)

QObject::moveToThread: Current thread (0x55806d5017a0) is not the object's thread (0x55806d8e21c0).
Cannot move to tar

In [35]:
# plt.imshow(frame[0:250,0:250, :])

### New Augmented Data

In [36]:
def data_aug(img):
    data = []
    for i in range(9):
        img = tf.image.stateless_random_brightness(img, max_delta=0.02, seed=(1,2))
        img = tf.image.stateless_random_contrast(img, lower=0.6, upper=1, seed=(1,3))
        # img = tf.image.stateless_random_crop(img, size=(20,20,3), seed=(1,2))
        img = tf.image.stateless_random_flip_left_right(img, seed=(np.random.randint(100),np.random.randint(100)))
        img = tf.image.stateless_random_jpeg_quality(img, min_jpeg_quality=90, max_jpeg_quality=100, seed=(np.random.randint(100),np.random.randint(100)))
        img = tf.image.stateless_random_saturation(img, lower=0.9,upper=1, seed=(np.random.randint(100),np.random.randint(100)))
            
        data.append(img)
    
    return data

In [37]:
import os
import uuid

In [39]:
img_path = os.path.join(ANC_PATH, '3a98b982-52d7-11ed-aeb1-91af58059082.jpg')
img = cv2.imread(img_path)
augmented_images = data_aug(img)

for image in augmented_images:
    cv2.imwrite(os.path.join(ANC_PATH, '{}.jpg'.format(uuid.uuid1())), image.numpy())

In [40]:
for file_name in os.listdir(os.path.join(POS_PATH)):
    img_path = os.path.join(POS_PATH, file_name)
    img = cv2.imread(img_path)
    augmented_images = data_aug(img) 
    
    for image in augmented_images:
        cv2.imwrite(os.path.join(POS_PATH, '{}.jpg'.format(uuid.uuid1())), image.numpy())

## Loading & Preprocessing Images

In [64]:
anchor = tf.data.Dataset.list_files(ANC_PATH+'/*.jpg').take(3000)
positive = tf.data.Dataset.list_files(POS_PATH+'/*.jpg').take(3000)
negative = tf.data.Dataset.list_files(NEG_PATH+'/*.jpg').take(3000)

In [68]:
dir_test = anchor.as_numpy_iterator()

In [69]:
print(dir_test.next())

b'data/anchor/d2d964a8-52d7-11ed-aeb1-91af58059082.jpg'


## Processing Images

In [3]:
def preprocess(file_path):
    
    # Read in image from file path
    byte_img = tf.io.read_file(file_path)
    # Load in the image 
    img = tf.io.decode_jpeg(byte_img)
    
    # Preprocessing steps - resizing the image to be 100x100x3
    img = tf.image.resize(img, (100,100))
    # Scale image to be between 0 and 1 
    img = img / 255.0

    # Return image
    return img

In [72]:
img = preprocess('data//anchor//d2d964a8-52d7-11ed-aeb1-91af58059082.jpg')

In [73]:
img.numpy().max()

0.78357846

### Creating Labelled Dataset

In [ ]:
# (anchor, positive) => 1,1,1,1,1
# (anchor, negative) => 0,0,0,0,0

In [75]:
positives = tf.data.Dataset.zip((anchor, positive, tf.data.Dataset.from_tensor_slices(tf.ones(len(anchor)))))
negatives = tf.data.Dataset.zip((anchor, negative, tf.data.Dataset.from_tensor_slices(tf.zeros(len(anchor)))))
data = positives.concatenate(negatives)

In [86]:
samples = data.as_numpy_iterator()

In [87]:
example = samples.next()

In [88]:
example

(b'data/anchor/dc702fa4-52d4-11ed-aeb1-91af58059082.jpg',
 b'data/positive/9d4c4b26-52d6-11ed-aeb1-91af58059082.jpg',
 1.0)

### Build Train and Test Partition

In [89]:
def preprocess_twin(input_img, validation_img, label):
    return(preprocess(input_img), preprocess(validation_img), label)

In [90]:
res = preprocess_twin(*example)

In [95]:
# plt.imshow(res[1])

In [96]:
res[2]

1.0

In [97]:
# Build dataloader pipeline

data = data.map(preprocess_twin)
data = data.cache()
data = data.shuffle(buffer_size=10000)

In [98]:
# Training partition

train_data = data.take(round(len(data)*.7))
train_data = train_data.batch(16)
train_data = train_data.prefetch(8)

In [99]:
# Testing partition

test_data = data.skip(round(len(data)*.7))
test_data = test_data.take(round(len(data)*.3))
test_data = test_data.batch(16)
test_data = test_data.prefetch(8)

## Model Setup

In [4]:
inp = Input(shape=(100,100,3), name='input_image')

In [5]:
c1 = Conv2D(64, (10,10), activation='relu')(inp)
m1 = MaxPooling2D(64, (2,2), padding='same')(c1)

c2 = Conv2D(128, (7,7), activation='relu')(m1)
m2 = MaxPooling2D(64, (2,2), padding='same')(c2)

c3 = Conv2D(128, (4,4), activation='relu')(m2)
m3 = MaxPooling2D(64, (2,2), padding='same')(c3)

c4 = Conv2D(256, (4,4), activation='relu')(m3)
f1 = Flatten()(c4)
d1 = Dense(4096, activation='sigmoid')(f1)

2022-10-25 20:04:32.943289: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
mod = Model(inputs=[inp], outputs=[d1], name='embedding')

In [7]:
mod.summary()

Model: "embedding"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_image (InputLayer)    [(None, 100, 100, 3)]     0         
                                                                 
 conv2d (Conv2D)             (None, 91, 91, 64)        19264     
                                                                 
 max_pooling2d (MaxPooling2D  (None, 46, 46, 64)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 40, 40, 128)       401536    
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 20, 20, 128)      0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 17, 17, 128)       26

In [8]:
def make_embedding(): 
    inp = Input(shape=(100,100,3), name='input_image')
    
    # First block
    c1 = Conv2D(64, (10,10), activation='relu')(inp)
    m1 = MaxPooling2D(64, (2,2), padding='same')(c1)
    
    # Second block
    c2 = Conv2D(128, (7,7), activation='relu')(m1)
    m2 = MaxPooling2D(64, (2,2), padding='same')(c2)
    
    # Third block 
    c3 = Conv2D(128, (4,4), activation='relu')(m2)
    m3 = MaxPooling2D(64, (2,2), padding='same')(c3)
    
    # Final embedding block
    c4 = Conv2D(256, (4,4), activation='relu')(m3)
    f1 = Flatten()(c4)
    d1 = Dense(4096, activation='sigmoid')(f1)
    
    
    return Model(inputs=[inp], outputs=[d1], name='embedding')

In [9]:
embedding = make_embedding()

In [10]:
embedding.summary()

Model: "embedding"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_image (InputLayer)    [(None, 100, 100, 3)]     0         
                                                                 
 conv2d_4 (Conv2D)           (None, 91, 91, 64)        19264     
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 46, 46, 64)       0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 40, 40, 128)       401536    
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 20, 20, 128)      0         
 2D)                                                             
                                                                 
 conv2d_6 (Conv2D)           (None, 17, 17, 128)       26

### Building Distance Layer

In [11]:
# Siamese L1 Distance class

class L1Dist(Layer):
    
    # Init method - inheritance
    def __init__(self, **kwargs):
        super().__init__()
       
    # Magic happens here - similarity calculation
    def call(self, input_embedding, validation_embedding):
        return tf.math.abs(input_embedding - validation_embedding)

In [12]:
l1 = L1Dist()

### Making Siamese Model

In [13]:
input_image = Input(name='input_img', shape=(100,100,3))
validation_image = Input(name='validation_img', shape=(100,100,3))

In [14]:
inp_embedding = embedding(input_image)
val_embedding = embedding(validation_image)

In [15]:
siamese_layer = L1Dist()

In [16]:
distances = siamese_layer(inp_embedding, val_embedding)

In [17]:
classifier = Dense(1, activation='sigmoid')(distances)

In [18]:
classifier

<KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'dense_2')>

In [19]:
siamese_network = Model(inputs=[input_image, validation_image], outputs=classifier, name='SiameseNetwork')

In [20]:
siamese_network.summary()

Model: "SiameseNetwork"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_img (InputLayer)         [(None, 100, 100, 3  0           []                               
                                )]                                                                
                                                                                                  
 validation_img (InputLayer)    [(None, 100, 100, 3  0           []                               
                                )]                                                                
                                                                                                  
 embedding (Functional)         (None, 4096)         38960448    ['input_img[0][0]',              
                                                                  'validation_img[0][

In [21]:
def make_siamese_model(): 
    
    # Anchor image input in the network
    input_image = Input(name='input_img', shape=(100,100,3))
    
    # Validation image in the network 
    validation_image = Input(name='validation_img', shape=(100,100,3))
    
    # Combine siamese distance components
    siamese_layer = L1Dist()
    siamese_layer._name = 'distance'
    distances = siamese_layer(embedding(input_image), embedding(validation_image))
    
    # Classification layer 
    classifier = Dense(1, activation='sigmoid')(distances)
    
    return Model(inputs=[input_image, validation_image], outputs=classifier, name='SiameseNetwork')

In [22]:
siamese_model = make_siamese_model()

In [23]:
siamese_model.summary()

Model: "SiameseNetwork"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_img (InputLayer)         [(None, 100, 100, 3  0           []                               
                                )]                                                                
                                                                                                  
 validation_img (InputLayer)    [(None, 100, 100, 3  0           []                               
                                )]                                                                
                                                                                                  
 embedding (Functional)         (None, 4096)         38960448    ['input_img[0][0]',              
                                                                  'validation_img[0][

## Training

In [127]:
# Setting up Loss and Optimizer

binary_cross_loss = tf.losses.BinaryCrossentropy()
opt = tf.keras.optimizers.Adam(1e-4) # 0.0001

In [128]:
# Establishing checkpoints

checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, 'ckpt')
checkpoint = tf.train.Checkpoint(opt=opt, siamese_model=siamese_model)

In [129]:
# Train Setup function

test_batch = train_data.as_numpy_iterator()
batch_1 = test_batch.next()
X = batch_1[:2]
y = batch_1[2]

In [130]:
y

array([1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.],
      dtype=float32)

In [131]:
@tf.function
def train_step(batch):
    
    # Record all of our operations 
    with tf.GradientTape() as tape:     
        # Get anchor and positive/negative image
        X = batch[:2]
        # Get label
        y = batch[2]
        
        # Forward pass
        yhat = siamese_model(X, training=True)
        # Calculate loss
        loss = binary_cross_loss(y, yhat)
    print(loss)
        
    # Calculate gradients
    grad = tape.gradient(loss, siamese_model.trainable_variables)
    
    # Calculate updated weights and apply to siamese model
    opt.apply_gradients(zip(grad, siamese_model.trainable_variables))
        
    # Return loss
    return loss

### Building Training Loop

In [132]:
# Importing metric calculations

from tensorflow.keras.metrics import Precision, Recall

In [133]:
def train(data, EPOCHS):
    # Loop through epochs
    for epoch in range(1, EPOCHS+1):
        print('\n Epoch {}/{}'.format(epoch, EPOCHS))
        progbar = tf.keras.utils.Progbar(len(data))
        
        # Creating a metric object 
        r = Recall()
        p = Precision()
        
        # Loop through each batch
        for idx, batch in enumerate(data):
            # Run train step here
            loss = train_step(batch)
            yhat = siamese_model.predict(batch[:2])
            r.update_state(batch[2], yhat)
            p.update_state(batch[2], yhat) 
            progbar.update(idx+1)
        print(loss.numpy(), r.result().numpy(), p.result().numpy())
        
        # Save checkpoints
        if epoch % 10 == 0: 
            checkpoint.save(file_prefix=checkpoint_prefix)

## Training the Model

In [134]:
EPOCHS = 50

In [135]:
train(train_data, EPOCHS)


 Epoch 1/50
Tensor("binary_crossentropy/weighted_loss/value:0", shape=(), dtype=float32)
Tensor("binary_crossentropy/weighted_loss/value:0", shape=(), dtype=float32)
132/132 [==============================] - 1560s 12s/step
0.011360118 0.84869057 0.99885845

 Epoch 2/50
132/132 [==============================] - 1539s 12s/step
0.00077219825 0.9980952 0.9990467

 Epoch 3/50
132/132 [==============================] - 1533s 12s/step
0.004429535 0.99421406 1.0

 Epoch 4/50
132/132 [==============================] - 1531s 12s/step
0.015225539 0.9894636 0.99231505

 Epoch 5/50
132/132 [==============================] - 1535s 12s/step
0.0017453289 0.99904215 1.0

 Epoch 6/50
132/132 [==============================] - 1527s 12s/step
0.004611539 1.0 1.0

 Epoch 7/50
132/132 [==============================] - 1522s 12s/step
0.0011538347 0.9981114 1.0

 Epoch 8/50
132/132 [==============================] - 1519s 12s/step
0.014474045 0.99717516 1.0

 Epoch 9/50
132/132 [==========================

## Model Evaluation

In [136]:
# Get a batch of test data

test_input, test_val, y_true = test_data.as_numpy_iterator().next()

In [137]:
y_hat = siamese_model.predict([test_input, test_val])

In [138]:
# Post processing the results

[1 if prediction > 0.5 else 0 for prediction in y_hat ]

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]

In [139]:
y_true

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
      dtype=float32)

## Calculate Metrics

In [140]:
# Creating a metric object 
m = Recall()

# Calculating the recall value 
m.update_state(y_true, y_hat)

# Return Recall Result
m.result().numpy()

1.0

In [141]:
# Creating a metric object 
m = Precision()

# Calculating the recall value 
m.update_state(y_true, y_hat)

# Return Recall Result
m.result().numpy()

1.0

In [142]:
r = Recall()
p = Precision()

for test_input, test_val, y_true in test_data.as_numpy_iterator():
    yhat = siamese_model.predict([test_input, test_val])
    r.update_state(y_true, yhat)
    p.update_state(y_true,yhat) 

print(r.result().numpy(), p.result().numpy())

0.9978166 1.0


## Results

In [146]:
# # Set plot size 
# plt.figure(figsize=(10,8))

# # Set first subplot
# plt.subplot(1,2,1)
# plt.imshow(test_input[0])

# # Set second subplot
# plt.subplot(1,2,2)
# plt.imshow(test_val[0])

# # Renders cleanly
# plt.show()

## Saving the Model

In [147]:
# Save weights

siamese_model.save('siamesemodelv1.h5')

In [24]:
L1Dist

__main__.L1Dist

In [25]:
# Reload model 
siamese_model = tf.keras.models.load_model('siamesemodelv1.h5', 
                                   custom_objects={'L1Dist':L1Dist, 'BinaryCrossentropy':tf.losses.BinaryCrossentropy})

In [26]:
# Make predictions with reloaded model

siamese_model.predict([test_input, test_val])

NameError: name 'test_input' is not defined

In [152]:
# View model summary

siamese_model.summary()

Model: "SiameseNetwork"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_img (InputLayer)         [(None, 100, 100, 3  0           []                               
                                )]                                                                
                                                                                                  
 validation_img (InputLayer)    [(None, 100, 100, 3  0           []                               
                                )]                                                                
                                                                                                  
 embedding (Functional)         (None, 4096)         38960448    ['input_img[0][0]',              
                                                                  'validation_img[0][

## Real Time Testing

In [9]:
# application_data/verification_images

In [27]:
os.listdir(os.path.join('application_data', 'verification_images'))

['1b94fabe-52d7-11ed-aeb1-91af58059082.jpg',
 '58a0930c-52d5-11ed-aeb1-91af58059082.jpg',
 '075eb9c8-52d6-11ed-aeb1-91af58059082.jpg',
 '2f804474-52d8-11ed-aeb1-91af58059082.jpg',
 '1a898d62-52d5-11ed-aeb1-91af58059082.jpg',
 '98b588a2-52d6-11ed-aeb1-91af58059082.jpg',
 '1de980b6-52d5-11ed-aeb1-91af58059082.jpg',
 '308c61cc-52d8-11ed-aeb1-91af58059082.jpg',
 '52c6051a-52d6-11ed-aeb1-91af58059082.jpg',
 '0d1cc1e8-52d6-11ed-aeb1-91af58059082.jpg',
 '99a4a7ca-52d6-11ed-aeb1-91af58059082.jpg',
 '63f0177c-52d6-11ed-aeb1-91af58059082.jpg',
 '53bed410-52d6-11ed-aeb1-91af58059082.jpg',
 '308cbfaa-52d8-11ed-aeb1-91af58059082.jpg',
 '61d4d4d2-52d6-11ed-aeb1-91af58059082.jpg',
 '51ada886-52d6-11ed-aeb1-91af58059082.jpg',
 '1ad3f332-52d7-11ed-aeb1-91af58059082.jpg',
 '0f474740-52d6-11ed-aeb1-91af58059082.jpg',
 '58caa542-52d6-11ed-aeb1-91af58059082.jpg',
 '2fa3cf84-52d8-11ed-aeb1-91af58059082.jpg',
 '64bbc304-52d6-11ed-aeb1-91af58059082.jpg',
 '2f77856e-52d8-11ed-aeb1-91af58059082.jpg',
 '1b473b5e

In [28]:
os.path.join('application_data', 'input_image', 'input_image.jpg')

'application_data/input_image/input_image.jpg'

In [29]:
for image in os.listdir(os.path.join('application_data', 'verification_images')):
    validation_img = os.path.join('application_data', 'verification_images', image)
    print(validation_img)

application_data/verification_images/1b94fabe-52d7-11ed-aeb1-91af58059082.jpg
application_data/verification_images/58a0930c-52d5-11ed-aeb1-91af58059082.jpg
application_data/verification_images/075eb9c8-52d6-11ed-aeb1-91af58059082.jpg
application_data/verification_images/2f804474-52d8-11ed-aeb1-91af58059082.jpg
application_data/verification_images/1a898d62-52d5-11ed-aeb1-91af58059082.jpg
application_data/verification_images/98b588a2-52d6-11ed-aeb1-91af58059082.jpg
application_data/verification_images/1de980b6-52d5-11ed-aeb1-91af58059082.jpg
application_data/verification_images/308c61cc-52d8-11ed-aeb1-91af58059082.jpg
application_data/verification_images/52c6051a-52d6-11ed-aeb1-91af58059082.jpg
application_data/verification_images/0d1cc1e8-52d6-11ed-aeb1-91af58059082.jpg
application_data/verification_images/99a4a7ca-52d6-11ed-aeb1-91af58059082.jpg
application_data/verification_images/63f0177c-52d6-11ed-aeb1-91af58059082.jpg
application_data/verification_images/53bed410-52d6-11ed-aeb1-91a

In [30]:
def verify(model, detection_threshold, verification_threshold):
    # Build results array
    results = []
    for image in os.listdir(os.path.join('application_data', 'verification_images')):
        input_img = preprocess(os.path.join('application_data', 'input_image', 'input_image.jpg'))
        validation_img = preprocess(os.path.join('application_data', 'verification_images', image))
        
        # Make Predictions 
        result = model.predict(list(np.expand_dims([input_img, validation_img], axis=1)))
        results.append(result)
    
    # Detection Threshold: Metric above which a prediciton is considered positive 
    detection = np.sum(np.array(results) > detection_threshold)
    
    # Verification Threshold: Proportion of positive predictions / total positive samples 
    verification = detection / len(os.listdir(os.path.join('application_data', 'verification_images'))) 
    verified = verification > verification_threshold
    
    return results, verified

## OpenCV Real time Verification

In [31]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    frame = frame[120:120+250,200:200+250, :]
    
    cv2.imshow('Verification', frame)
    
    # Verification trigger
    if cv2.waitKey(10) & 0xFF == ord('v'):
        # Save input image to application_data/input_image folder 
#         hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
#         h, s, v = cv2.split(hsv)

#         lim = 255 - 10
#         v[v > lim] = 255
#         v[v <= lim] -= 10
        
#         final_hsv = cv2.merge((h, s, v))
#         img = cv2.cvtColor(final_hsv, cv2.COLOR_HSV2BGR)

        cv2.imwrite(os.path.join('application_data', 'input_image', 'input_image.jpg'), frame)
        # Run verification
        results, verified = verify(siamese_model, 0.5, 0.5)
        print(verified)
    
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x55eda46af190) is not the object's thread (0x55eda409ff80).
Cannot move to target thread (0x55eda46af190)

QObject::moveToThread: Current thread (0x55eda46af190) is not the object's thread (0x55eda409ff80).
Cannot move to target thread (0x55eda46af190)

QObject::moveToThread: Current thread (0x55eda46af190) is not the object's thread (0x55eda409ff80).
Cannot move to target thread (0x55eda46af190)

QObject::moveToThread: Current thread (0x55eda46af190) is not the object's thread (0x55eda409ff80).
Cannot move to target thread (0x55eda46af190)

QObject::moveToThread: Current thread (0x55eda46af190) is not the object's thread (0x55eda409ff80).
Cannot move to target thread (0x55eda46af190)

QObject::moveToThread: Current thread (0x55eda46af190) is not the object's thread (0x55eda409ff80).
Cannot move to target thread (0x55eda46af190)

QObject::moveToThread: Current thread (0x55eda46af190) is not the object's thread (0x55eda409ff80).
Cannot move to tar

True
False
True
False


In [40]:
# np.sum(np.squeeze(results) > 0.9)

In [41]:
results

[array([[5.2963316e-07]], dtype=float32),
 array([[2.7554414e-09]], dtype=float32),
 array([[7.456064e-07]], dtype=float32),
 array([[0.00058356]], dtype=float32),
 array([[2.055235e-06]], dtype=float32),
 array([[2.206267e-07]], dtype=float32),
 array([[1.7330075e-07]], dtype=float32),
 array([[1.13492455e-07]], dtype=float32),
 array([[6.346709e-08]], dtype=float32),
 array([[8.47238e-07]], dtype=float32),
 array([[1.8893253e-06]], dtype=float32),
 array([[1.7793922e-06]], dtype=float32),
 array([[1.5796068e-08]], dtype=float32),
 array([[7.92463e-06]], dtype=float32),
 array([[1.04364474e-07]], dtype=float32),
 array([[1.1165282e-07]], dtype=float32),
 array([[1.4956216e-08]], dtype=float32),
 array([[1.2052584e-06]], dtype=float32),
 array([[3.2553057e-08]], dtype=float32),
 array([[0.00050032]], dtype=float32),
 array([[1.9989432e-07]], dtype=float32),
 array([[5.108625e-05]], dtype=float32),
 array([[3.2388917e-07]], dtype=float32),
 array([[1.217896e-07]], dtype=float32),
 array